spring:
  application:
    name: ErrorFreeText

  datasource:
    url: jdbc:postgresql://localhost:5432/error_free    #jdbc:postgresql://db:5432/error_free
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 25
        order_inserts: true
        format_sql: true

app:
  yandex-speller:
    base-url: https://speller.yandex.net/services/spellservice.json/checkTexts
    connect-timeout: 5000
    read-timeout: 5000
  scheduler.delay-ms: 5000
  text-splitter:
    max-chunk-size: 10000
server:
  port: 8080
